#pragma once

#include <Arduino.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/i2s.h"
#include "IAcousticOutput.h"

// Minimal PCM5102 driver: I2S TX with a stream buffer for ISR-to-task handoff.
// Accepts 8-bit centered samples (0..255, 128=0) and converts to signed 16-bit stereo.
class PCM5102Driver : public IAcousticOutput {
public:
  using SampleCallback = uint8_t(*)(void* ctx);
  using SampleCallback16 = int16_t(*)(void* ctx);
  void attachPins(int bck, int lrck, int data) {
    _pin_bck = bck;
    _pin_lrck = lrck;
    _pin_data = data;
  }

  void begin(uint32_t sampleRateHz) override;

  void IRAM_ATTR writeFromISR(uint8_t sample8) override;
  void write(uint8_t sample8) override;

  // Minimal blocking sine test directly to I2S (bypasses ring buffer and writer task)
  void testMinimal(uint32_t freqHz = 1000, float seconds = 3.0f, float amplitude = 0.6f);

  // Continuous pure sine generated by the writer task (exercises I2S pipeline only)
  void startPureSine(uint32_t freqHz = 1000, float amplitude = 0.6f);
  void stopPureSine();
  bool isPureSineActive() const { return _sineActive; }

  // Diagnostics
  void resetStats();
  void getStats(uint32_t& dropsFromISR, uint32_t& underruns, size_t& minAvail, size_t& maxAvail) const;

  // Pull-mode sample source (single clock domain generation)
  void setSampleSource(SampleCallback cb, void* ctx) { _cb = cb; _cbCtx = ctx; }
  void setSampleSource16(SampleCallback16 cb16, void* ctx) { _cb16 = cb16; _cbCtx = ctx; }

private:
  static void writerTaskThunk(void* arg) {
    static_cast<PCM5102Driver*>(arg)->writerTask();
  }
  void writerTask();

  // I2S
  i2s_port_t _port = I2S_NUM_0;
  int _pin_bck = 26;
  int _pin_lrck = 27;
  int _pin_data = 25;
  uint32_t _sampleRate = 64000;

  // Lock-free ring buffer (single producer ISR, single consumer task)
  static constexpr size_t RB_SIZE = 65536; // bytes, power of two (~256 ms @48kHz)
  uint8_t _rb[RB_SIZE];
  volatile size_t _head = 0; // write index (ISR)
  volatile size_t _tail = 0; // read index  (task)

  TaskHandle_t _task = nullptr;

  // Pure sine generation state (writer task domain)
  volatile bool _sineActive = false;
  float _sineFreq = 1000.0f;
  float _sineAmp = 0.6f; // 0..1
  float _sinePhase = 0.0f;

  // Diagnostics
  volatile uint32_t _dropsFromISR = 0;
  volatile uint32_t _underruns = 0;
  volatile size_t _minAvail = (size_t)-1;
  volatile size_t _maxAvail = 0;

  // Optional pull-mode callback
  SampleCallback _cb = nullptr;
  SampleCallback16 _cb16 = nullptr;
  void* _cbCtx = nullptr;
};
